### ISSUE TITLE
Ensure we follow security best practices

### ISSUE THREAD

**Issue by sindresorhus** [lukechilds/hyperdex#10]
We need to make sure we follow the best practices for security before the public launch: https://github.com/electron/electron/blob/master/docs/tutorial/security.md#checklist

**Comment by lukechilds** [comment]
We should look into disabling Node.js integration in the render process and do all render <=> Node.js communication via message passing: https://github.com/lukechilds/hyperdex/pull/209#issuecomment-389042098

**Comment by sindresorhus** [comment]
And enable `contextIsolation`.

**Comment by lukechilds** [comment]
Also, even if we isolate the process completely, an XSS attack could still steal the users balances, there's no way to protect against that (apart from taking measures against XXS in the first place which we already have).

So this would just make an absolutely terrible situation slightly less terrible.

**Comment by lukechilds** [comment]
In fact this issue can be closed because I think we've satisfied the title of `Ensure we follow security best practices`.

I'll create a new issue for process isolation.
