### ISSUE TITLE
Codesign the app

### ISSUE THREAD

**Issue by sindresorhus** [lukechilds/hyperdex#211]
See: https://www.electron.build/code-signing

We can set it up in Travis, but we need certificates for macOS (easy) and Windows (hard).

The priority is getting macOS codesigning set up as it currently makes it difficult to open the app without. (The 0.1.0 milestone is for macOS only)

- [x] macOS
- [ ] Windows

**Comment by lukechilds** [comment]
What's the drawback of not codesigning with Windows?

**Comment by sindresorhus** [comment]
@lukechilds I don't think it's worth the effort to codesign on Windows: https://github.com/ImageOptim/gifski/releases/tag/0.8.3

**Comment by lukechilds** [comment]
Wow. Yeah, lets not do that.

No Windows testers have even mentioned issues about signing anyway. (AFAIK)
