### ISSUE TITLE
Cursor jumping to the end on seed confirm page

### ISSUE THREAD

**Issue by gcharang** [lukechilds/hyperdex#237]
When creating a new portfolio, on the seed confirm page, after a few words are entered, if an attempt is made to edit the previous words (i.e., entering text in between the already entered words), after entering a single letter, the cursor jumps to the end of the line.
![Demo](https://user-images.githubusercontent.com/21151592/40268087-e4e1ada8-5b84-11e8-9298-4040a68b8a69.gif)
---

HyperDEX Nightly 0.0.0-536c5dd-18.5.18.1358
Electron 2.0.1
linux 4.13.0-41-generic
Locale: en-GB

**Comment by sindresorhus** [comment]
Thanks for reporting. I'm working on a fix.
