### ISSUE TITLE
After re-installation/upgrade ! 

### ISSUE THREAD

**Issue by ip-config** [lukechilds/hyperdex#256]
Hello,
after re-installation/upgrade saved profiles are disappeared!
trading/swaps history disappeared!
regards
HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
I assume you upgraded from the nightly builds? The nightly builds and this one are separate and store the portfolios in separate locations. You can have both installed at the same time (although not running at the same time).

**Comment by ip-config** [comment]
i get it 
thanks
