### ISSUE TITLE
Cancelling an order appears to be unresponsive

### ISSUE THREAD

**Issue by FundazuSafu** [lukechilds/hyperdex#258]
Cancelling an order appears to be unresponsive. The color toggles on click, but doesn't seem to run the intended process.

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0

**Comment by sindresorhus** [comment]
What is the status of the order when you click "Cancel"? (Pending, Swap 1/4, etc)

**Comment by FundazuSafu** [comment]
pending

**Comment by lukechilds** [comment]
This is a bug in `marketmaker`, more info here: https://github.com/lukechilds/hyperdex/issues/129
