### ISSUE TITLE
Hyperdex login issue, possibly related to changing default showing trading pairs.

### ISSUE THREAD

**Issue by Jcharming** [lukechilds/hyperdex#259]
Windows 8.1

Issue: HyperDex will not allow me to log in.  Stalled at splash screen 'Logging in...'

Downloaded hyperdex.
Created a portfolio and logged in.
Deposited Beer from faucet into portfolio.
Went to preferences and adjusted what default coins I could see listed.
Exited hyperdex.
Reopened hyperdex and put in login information, >problem start.

Additional steps:  After final step above, closed hyperdex, reopened and entered login information. Problem persisted. 

_Below: Current View_
![image](https://user-images.githubusercontent.com/39496354/40320515-9a11a3a0-5cf1-11e8-8355-acc012ecffe1.png)

      
_Below: Error box that may or may not be related to event. Error box appears after entering portfolio login information, however did not prevent logging into the platform during the first success._ 

![image](https://user-images.githubusercontent.com/39496354/40320590-d1858c5c-5cf1-11e8-8e3d-2a072875b4d0.png)

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 6.3.9600
Locale: en-US

**Comment by sindresorhus** [comment]
In the "Developer Tools" window behind HyperDEX, can you go to the "Console" tab and copy-paste all of its contents?

**Comment by sindresorhus** [comment]
In the app menu (at the top), find the "Debug" menu and select "Show Preferences". Can you copy-paste what it contains here?

**Comment by gidonro** [comment]
I'm having the same issue:
Unhandled Promise Rejection
TypeError: Cannot read property 'focus' of null
    at app://-/bundle.js:88338:38
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:88255:191)
    at app://-/bundle.js:88255:361
    at <anonymous>

**Comment by Jcharming** [comment]
**_## Console tab preview & contents_**

![image](https://user-images.githubusercontent.com/39496354/40388924-8299d7ca-5dd6-11e8-91df-b0958d884037.png)


`api.js:31 Fetch API cannot load app://-/eth. URL scheme "app" is not supported.
(anonymous) @ api.js:31
run @ index.js:99
Promise @ index.js:116
add @ index.js:94
(anonymous) @ api.js:31
step @ browser.js:32
(anonymous) @ browser.js:32
(anonymous) @ browser.js:32
_request @ api.js:28
(anonymous) @ api.js:53
step @ browser.js:32
(anonymous) @ browser.js:32
Promise resolved (async)
step @ browser.js:32
(anonymous) @ browser.js:32
(anonymous) @ browser.js:32
request @ api.js:52
(anonymous) @ api.js:44
step @ browser.js:32
(anonymous) @ browser.js:32
Promise resolved (async)
step @ browser.js:32
(anonymous) @ browser.js:32
(anonymous) @ browser.js:32
enableSocket @ api.js:42
(anonymous) @ Login.js:86
step @ App.js:230
(anonymous) @ App.js:230
Promise resolved (async)
step @ App.js:230
(anonymous) @ App.js:230
Promise resolved (async)
step @ App.js:230
(anonymous) @ App.js:230
(anonymous) @ App.js:230
handleLogin @ Login.js:76
(anonymous) @ LoginBox.js:54
step @ react-select.es.js:2663
(anonymous) @ react-select.es.js:2663
(anonymous) @ react-select.es.js:2663
value @ LoginBox.js:12
ma @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
Ga @ react-dom.production.min.js:20
Ka @ react-dom.production.min.js:22
Ma @ react-dom.production.min.js:22
Ia @ react-dom.production.min.js:21
Pa @ react-dom.production.min.js:24
Qa @ react-dom.production.min.js:24
Ud @ react-dom.production.min.js:83
batchedUpdates @ react-dom.production.min.js:187
ec @ react-dom.production.min.js:42
Yd @ react-dom.production.min.js:85
interactiveUpdates @ react-dom.production.min.js:188
Xd @ react-dom.production.min.js:84
LoginBox.js:56 TypeError: Failed to fetch
    at api.js:31
    at run (index.js:99)
    at Promise (index.js:116)
    at new Promise (<anonymous>)
    at PQueue.add (index.js:94)
    at api.js:31
    at Generator.next (<anonymous>)
    at step (browser.js:32)
    at browser.js:32
    at new Promise (<anonymous>)
(anonymous) @ LoginBox.js:56
step @ react-select.es.js:2663
(anonymous) @ react-select.es.js:2663
Promise rejected (async)
step @ react-select.es.js:2663
(anonymous) @ react-select.es.js:2663
(anonymous) @ react-select.es.js:2663
value @ LoginBox.js:12
ma @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
Ga @ react-dom.production.min.js:20
Ka @ react-dom.production.min.js:22
Ma @ react-dom.production.min.js:22
Ia @ react-dom.production.min.js:21
Pa @ react-dom.production.min.js:24
Qa @ react-dom.production.min.js:24
Ud @ react-dom.production.min.js:83
batchedUpdates @ react-dom.production.min.js:187
ec @ react-dom.production.min.js:42
Yd @ react-dom.production.min.js:85
interactiveUpdates @ react-dom.production.min.js:188
Xd @ react-dom.production.min.js:84
index.js:29 TypeError: Cannot read property 'focus' of null
    at LoginBox.js:65
    at Generator.next (<anonymous>)
    at step (react-select.es.js:2663)
    at react-select.es.js:2663
    at <anonymous>
handleError @ index.js:29
reason @ index.js:71
invokeFunc @ index.js:160
trailingEdge @ index.js:207
timerExpired @ index.js:195
setTimeout (async)
leadingEdge @ index.js:168
debounced @ index.js:235
window.addEventListener.event @ index.js:75`

**_## Debug Menu > Show Preferences Preview and Contents_**

![image](https://user-images.githubusercontent.com/39496354/40389387-e9fab3ca-5dd7-11e8-9236-4e918f1cd801.png)

`{
	"windowState": {
		"width": 1060,
		"height": 650
	},
	"darkMode": true,
	"enabledCoins": [
		"BEER",
		"BTC",
		"CHIPS",
		"DOGE",
		"KMD",
		"PIZZA",
		"SUPERNET",
		"REVS"
	],
	"lastActivePortfolioId": "jcharming-4beb7f",
	"hasShownExchangeIntro": true,
	"marketmakerUrl": "eth"
}`

**Comment by lukechilds** [comment]
@Jcharming You set "eth" as your custom `marketmaker` url. That's why the app won't start. You need to change your `config.json` to:

```js
{  
   "windowState":{  
      "width":1060,
      "height":650
   },
   "darkMode":true,
   "enabledCoins":[  
      "BEER",
      "BTC",
      "CHIPS",
      "DOGE",
      "KMD",
      "PIZZA",
      "SUPERNET",
      "REVS"
   ],
   "lastActivePortfolioId":"jcharming-4beb7f",
   "hasShownExchangeIntro":true
}
```

**Comment by sindresorhus** [comment]
I've made sure this doesn't happen again. We now validate that option: https://github.com/lukechilds/hyperdex/commit/869922313c90e11fb241229fa7d26df57c2e58ed
