### ISSUE TITLE
Missing Denarius (DNR)

### ISSUE THREAD

**Issue by carsenk** [lukechilds/hyperdex#261]
Denarius (DNR) is missing from the list of coins able to be swapped/added in the HyperDEX.

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
linux 4.13.0-38-generic
Locale: en-US

**Comment by carsenk** [comment]
Electrum IPs are incorrect, please update to these:

144.202.95.223 (Port 50001)
45.77.137.111 (Port 50001)

**Comment by sindresorhus** [comment]
@carsenk I got the Electrum IPs from https://github.com/jl777/coins/blob/master/electrums/DNR That's where we got all the Electrum servers. Can you update that one first? So I can confident it's correct ;)

**Comment by carsenk** [comment]
@sindresorhus Well I was going to put a PR up there as well, but looks like cipi beat me to it :package: 

https://github.com/jl777/coins/pull/55
