### ISSUE TITLE
Soft logout/login <profile switch>

### ISSUE THREAD

**Issue by ip-config** [lukechilds/hyperdex#266]
Hello,
1>> soft/session logout missing !
2>> or we can use switch bet profiles without close app and relaunch !
regads

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
1. Select "Log Out" in the "Portfolio" app menu (At the top).

**Comment by ip-config** [comment]
Found thanks
