### ISSUE TITLE
Small UI bug when setting up price/amount/total in the Exchange view

### ISSUE THREAD

**Issue by barbierir** [lukechilds/hyperdex#268]
OS: Ubuntu 18.04 with HyperDex .deb installer
When setting up a trade, the Total doesn't update if I first set the Amount and then the Price

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
linux 4.15.0-20-generic
Locale: it

**Comment by sindresorhus** [comment]
Thanks for reporting. Confirmed.

**Comment by lukechilds** [comment]
@sindresorhus Is this resolved? It works for me in master.

**Comment by sindresorhus** [comment]
@lukechilds The issue is still reproducible in master. If you set `Amount` and then `Price`, it updates the `Amount` field instead of `Total`.

**Comment by lukechilds** [comment]
I'm still not seeing it:

<img width="292" src="https://user-images.githubusercontent.com/2123375/40836434-f2be2f5a-65c0-11e8-8ea8-64fbda201a36.gif" />

**Comment by sindresorhus** [comment]
@lukechilds Set `Amount` to `10` and `Price` to `100` and you'll see it.

**Comment by lukechilds** [comment]
Ah yes, confirmed 👍

**Comment by kevva** [comment]
It's because `total` is mutated in `handlePriceChange`, and afterwards `handleTotalChange` is called with the old value. Ideally you'd only mutate the state in one place when handling events to avoid side effects like these.

I'll create a PR with a fix.
