### ISSUE TITLE
GUI problems only

### ISSUE THREAD

**Issue by dudezmobi** [lukechilds/hyperdex#273]
---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
darwin 17.4.0
Locale: en-US

**Comment by sindresorhus** [comment]
Thanks for helping us test HyperDEX and providing feedback :raised_hands:
Would you be able to elaborate a bit more on this issue?

**Comment by dudezmobi** [comment]
exchange click VIEW, THEN maximize screen. the flicker happens

**Comment by lukechilds** [comment]
The "view" button on a swap to open the swap modal?

Can you create a GIF of that happening, I can't recreate the issue.

**Comment by lukechilds** [comment]
do you mean it just takes a while for the layout to reflow while the screen is maximised?

**Comment by lukechilds** [comment]
Like this:

![kapture 2018-05-22 at 19 16 16](https://user-images.githubusercontent.com/2123375/40361789-b0bc99c6-5df4-11e8-9dde-93e85cd39ecc.gif)

**Comment by dudezmobi** [comment]
yes you got it right, i am still downloading screen capture with my test unit.

the view display on my screen has horizontal and vertical scroll 

![screen shot 2018-05-22 at 8 31 09 pm](https://user-images.githubusercontent.com/37325051/40362460-30f9e0a8-5dff-11e8-82d5-7960c748200a.png)

**Comment by lukechilds** [comment]
There's not much we can do about the laggy reflow I don't think. Possibly add a blur to the entire window when resizing and the deblur once it's reflowed to make it less noticeable? That's probably more effort than it's worth though. @sindresorhus?

Horizontal scrollbars shouldn't be appearing on that view. We'll take a look in to that. Thanks for reporting!

**Comment by lukechilds** [comment]
Are the scrollbars only there when you maximise with the modal open?

If you open/close when the modal is normal/fullscreen does you still see the scrollbars?

**Comment by dudezmobi** [comment]
The scrollbars are there on the modal view on Main program normal window size and also on maximise window size. On normal window size the modal view has big scrollbars.

Yes, still happens when i open close the modal view window in normal/fullscreen

![screen shot 2018-05-23 at 5 59 30 am](https://user-images.githubusercontent.com/37325051/40392531-838d2ab0-5e4e-11e8-8c11-076e768362cb.png)
![screen shot 2018-05-23 at 5 59 37 am](https://user-images.githubusercontent.com/37325051/40392533-84470318-5e4e-11e8-87bd-5b1ba2e499cb.png)

**Comment by sindresorhus** [comment]
I didn't account for users having wide always visible scrollbars on macOS. I'll just slightly increase the width of the modal dialog to fix this.

**Comment by lukechilds** [comment]
@sindresorhus But it looks like the horizontal scroll bar is there even though it can't scroll horizontally. There's no dragger thing in the horizontal scrollbar. 🤔

**Comment by sindresorhus** [comment]
@lukechilds Yes, also needs `overflow-x: hidden`. I have an incoming PR for this.
