### ISSUE TITLE
Balance during swap

### ISSUE THREAD

**Issue by dudezmobi** [lukechilds/hyperdex#274]
---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
darwin 17.4.0
Locale: en-US

**Comment by sindresorhus** [comment]
Thanks for helping us test HyperDEX and providing feedback :raised_hands:
Would you be able to elaborate a bit more on this issue?

**Comment by dudezmobi** [comment]
the swap did not got finished until now. 1900H. balance is ok but swap did not push through...

**Comment by dudezmobi** [comment]
il close this and test this pattern again.

**Comment by lukechilds** [comment]
@dudezmobi Are you saying the swap failed, and after a few hours your balance was back to normal but the UI was still just showing as failed?
