### ISSUE TITLE
Canceling Trades

### ISSUE THREAD

**Issue by blacktshirtreview** [lukechilds/hyperdex#285]
Attempting to trade BEER for PIZZA, is there any way to cancel the order once it goes into pending?

The platform looks great!  Much better than the Barterdex interface.

Good Luck!

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.17134
Locale: en-US

**Comment by sindresorhus** [comment]
Thanks for your feedback 🙌

Go to the "Trades" view and you should see a "Cancel" button for your order. We plan to add a "Cancel" button in the Exchange view too, follow #262.

**Comment by blacktshirtreview** [comment]
Thank you I see it, sounds good to me!

**Comment by lukechilds** [comment]
@blacktshirtreview Just a note, you can only cancel a trade while it's pending.

As soon as it's matched you can no longer cancel, this is a limitation of `marketmaker`, not the GUI.
