### ISSUE TITLE
Initiated a swap within 1 min from another swap request

### ISSUE THREAD

**Issue by dudezmobi** [lukechilds/hyperdex#293]
see screenshot, the time and date of the swap request
![screen shot 2018-05-23 at 7 09 24 am](https://user-images.githubusercontent.com/37325051/40394978-794f26ca-5e58-11e8-843f-d4fe17712769.png)

**Comment by lukechilds** [comment]
Thanks for helping us test HyperDEX and providing feedback 🙌
Would you be able to elaborate a bit more on this issue?

**Comment by dudezmobi** [comment]
Look at the latest swaps May 23 2018, i was able to initiate a swap within the same minute. one would be pending and the other one unmatched... The 1 min per swap checking did not happen during the placement of my order. (both are BEER/PIZZA one is pending and the other one is unmatched)

**Comment by lukechilds** [comment]
That sounds like an issue with the `marketmaker` daemon, unrelated to the GUI.

We just send a request to it when you click the order button. It's in charge of telling us if the order can be placed or not.

Either it's a bug in mm and it should of told you to wait. Or the time limit elapsed and everything happened as expected but your second order just wasn't matched.
