### ISSUE TITLE
great job BUT.....

### ISSUE THREAD

**Issue by sublime9182** [lukechilds/hyperdex#294]
---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
darwin 17.3.0
Locale: en-US

**Comment by sindresorhus** [comment]
Thanks for helping us test HyperDEX and providing feedback :raised_hands:
Would you be able to elaborate a bit more on this issue?

**Comment by sublime9182** [comment]
I actually had a misunderstanding of how it worked it was cleared up by
ptyx I was getting utxo error messages and couldn't find a manual utxo
splitter so I assumed I would have to create my utxos by making multiple
transactions it was explained to me that the utxo process in automated and
that I just need to restart hyperdex. After that I was able to successfully
complete trades. However on a small note two of the trades I completed
never showed 5/5 they got stuck on 3/5 but the trade DID go through so
maybe just a visual error with the interface?

**Comment by sublime9182** [comment]
Hi,

I've just signed the following petition "#FreeRossPetition: We Seek
@POTUS’s Clemency for Ross Ulbricht, Serving Double Life—without parole—for
a Website. @RealDonaldTrump @Free_Ross" and wanted to see if you could help
by adding your name.

Our goal is to reach 7,500 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2KYBxvf

Thanks!
William
