### ISSUE TITLE
The seed field on restore portfolio doesn't allow paste

### ISSUE THREAD

**Issue by jdmarlow86** [lukechilds/hyperdex#316]
When restoring a portfolio I am unable to paste a seed into the "Enter your Seed Phrase" screen.
Users will find this very cumbersome.

![image](https://user-images.githubusercontent.com/22251770/40554750-bc0f608e-6014-11e8-9516-8394ea4fd3a4.png)

![image](https://user-images.githubusercontent.com/22251770/40554806-e7cbba88-6014-11e8-905f-aee9224e88f8.png)

HyperDEX 0.1.0-alpha.2
Electron 2.0.2
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
How are you trying to paste it? Ctrl+V or right-click and then "Paste"?

**Comment by jdmarlow86** [comment]
Both

**Comment by lukechilds** [comment]
@sindresorhus there was another report of this previously. I can't seem to find the issue now but I'm pretty sure it was on Windows too.
