### ISSUE TITLE
impossible to withdraw BTCZ

### ISSUE THREAD

**Issue by cryptograal** [lukechilds/hyperdex#324]
Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 10000,
  complete: false }
    at errorWithObject (app://-/bundle.js:90100:46)
    at app://-/bundle.js:90357:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:90089:191)
    at app://-/bundle.js:90089:361
    at <anonymous>

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.17134
Locale: fr

**Comment by lukechilds** [comment]
Closing as this is a duplicate of https://github.com/lukechilds/hyperdex/issues/302
