### ISSUE TITLE
Order stuck in pending for days

### ISSUE THREAD

**Issue by blacktshirtreview** [lukechilds/hyperdex#327]
I attempted to execute an OOT/BTC swap at 00:12 24/05/18 and it's still stuck in pending.  When I click cancel nothing happens.  I've tried over a few days now please advise.

**Comment by blacktshirtreview** [comment]
was able to withdraw OOT today, the transaction is still stuck in pending though

**Comment by lukechilds** [comment]
Closing as it's a duplicate of https://github.com/lukechilds/hyperdex/issues/279
