### ISSUE TITLE
Screen readjusted after trading GUI problems only

### ISSUE THREAD

**Issue by dudezmobi** [lukechilds/hyperdex#328]
When error "Only one pending swap at a time" appears left hand side Beer Sell Order windows got smaller

![screen shot 2018-05-29 at 4 56 32 pm](https://user-images.githubusercontent.com/37325051/40648601-6b258de2-6361-11e8-8cf8-5f8dfdbdda5b.png)

**Comment by dudezmobi** [comment]
the error message could be a popup. easy to see and interact, less clutter on the main window

**Comment by sindresorhus** [comment]
We try to avoid modals whenever we can. Modals block all interaction and require you to dismiss them. Better to have the error message in the context of the action. Happy to consider other suggestions, but I don't think we should change anything here.

**Comment by sindresorhus** [comment]
We've decided to use a system notification for this instead. We'll also shake the button to make it clear something failed. Thanks for your feedback.

**Comment by dudezmobi** [comment]
noice 👍
