### ISSUE TITLE
Coins with same deposit address

### ISSUE THREAD

**Issue by jdmarlow86** [lukechilds/hyperdex#331]
36 out of the 49 active coins in my portfolio are duplicated - ex. BTG and GAME, BTC and CRW.
BEER and PIZZA example below. The full list of duplicates are color coded here https://docs.google.com/spreadsheets/d/1WTWgJrshJGHmwbHqtrJNq8kIBatvwOTl1PILvSya9dA/edit?usp=sharing

![image](https://user-images.githubusercontent.com/22251770/40665314-eb67759c-632a-11e8-98e9-32b4aaa0a900.png)
![image](https://user-images.githubusercontent.com/22251770/40665321-f3c836ae-632a-11e8-88aa-918fa9fc05ec.png)

version: 0.1.0-alpha2
OS: windows
Error msgs: None

**Comment by lukechilds** [comment]
That's expected, those coins use the same parameters for generating addresses and the underlying `marketmaker` daemon uses the same key pair for all currencies.

If you pass the same public key through the address generation algorithm with the same parameters you will get the same address.

This is how `marketmaker` works and is unrelated to the GUI.
