### ISSUE TITLE
Cancel button on Open Orders view

### ISSUE THREAD

**Issue by jdmarlow86** [lukechilds/hyperdex#345]
The cancel button on the Open Orders view doesn't seem to be functional.

Steps:
1. Create a BEER/PIZZA swap
2. While order is in Pending go to the Open Orders view
3. Select Cancel (button becomes grayed out)
4. Go back to the Exchange view then return to Open Orders view
5. Cancel button is now selectable again and Pending order remains

![image](https://user-images.githubusercontent.com/22251770/41109823-ebbed9c8-6a45-11e8-942a-711d00eeb45d.png)
![image](https://user-images.githubusercontent.com/22251770/41109862-04abcffe-6a46-11e8-948a-bff9910bdb29.png)

Version: 0.1.0-alpha.5
OS: Windows 10
Errors: none

**Comment by lukechilds** [comment]
Thanks for reporting, we're aware, this is a limitation in `marketmaker`.

More info here: https://github.com/lukechilds/hyperdex/issues/262#issuecomment-395390245
