### ISSUE TITLE
Can't login on Hyperdex alpha 0.6

### ISSUE THREAD

**Issue by VONLUEAPS** [lukechilds/hyperdex#356]
Unhandled Promise Rejection
ArgumentError: Expected string `symbol` to match `/^[A-Z]+$/`, got `EMC2`
    at app://-/bundle.js:90822:45
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:90730:191)
    at app://-/bundle.js:90730:437
    at new Promise (<anonymous>)
    at app://-/bundle.js:90730:99
    at Api.enableCurrency (app://-/bundle.js:90858:5)
    at app://-/bundle.js:1111:16
    at Array.map (<anonymous>)
    at app://-/bundle.js:1110:94

**Comment by sindresorhus** [comment]
We added stricter input checking and I forgot to consider that currency symbols can contain numbers. Until the next alpha, you can remove `EMC2` by clicking "Debug" in the app menu, and then click "Show settings", then remove `EMC2` from `enabledCoins` and save. Then restart HyperDEX and you should be able to login again.
